### ISSUE TITLE
Overscroll

### ISSUE THREAD

**Issue by tgadler** [axelkirken/eminenthemsida#10]
Det finns en paramter som heter "overscroll", ska vi sätta den till none för allt?

**Comment by axelkirken** [comment]
Uppfattar jag det rätt som att det gör att man inte kan "dra upp/ner" utanför sidan? 
Är det inte en fördel att ex. kunna dra ner på telefon för att ladda om sidan som vanligt?

**Comment by tgadler** [comment]
Det ser bara lite lustigt ut med menyn om man drar upp förbi den. Dock så är ju det smådetaljer.

**Comment by axelkirken** [comment]
Tycker det ser okej ut på telefon, kan inte skrolla förbi på dator. Vi kan diskutera på utvecklingsmötet
