### ISSUE TITLE
Expanderande om-oss-sektion

### ISSUE THREAD

**Issue by axelkirken** [axelkirken/eminenthemsida#2]
Lägga till funktionen att öppna/stänga om-oss-texten som i squarespace-varianten. Kan göras med html-tag "details" men blir tråkig animation.

**Comment by tgadler** [comment]
Det här kanske är överflödigt egentligen? Tåls att diskutera vid den stundande konferensen.

**Comment by tgadler** [comment]
Stängs efter överläggning vid scrum-möte.
