### ISSUE TITLE
Fixa så elementen i navbaren beter sig

### ISSUE THREAD

**Issue by tgadler** [axelkirken/eminenthemsida#6]
- Gör så hela .header får en lämplig höjd
- Låt loggan ockupera lämplig mängd av det, centrerad vertikalt
- Låt <li>-elementen ockupera 100% av .header. (Schysst när man hovrar över dem) Deras text bör vara centrerad vertikalt.

**Comment by axelkirken** [comment]
Inte helt säker på att jag förstår vad som menas med alla punkter så gör inga större åtgärder före utvecklingsmöte. För vertikal positionering, se ändring i css där vi använder calc(50% - elementets halva höjd). tillsammans med absolut positionering. Ett annat alternativ som kan vara värt att köra för att förenkla positionering vertikalt kan vara med ett gridsystem (https://css-tricks.com/snippets/css/complete-guide-grid/) eller flexbox (https://css-tricks.com/snippets/css/a-guide-to-flexbox/).

Glöm inte mobile-first
