### ISSUE TITLE
Nedre raden i textsnurran är inte centrerad

### ISSUE THREAD

**Issue by tgadler** [axelkirken/eminenthemsida#8]
<img width="526" alt="Skärmavbild 2022-07-14 kl  20 47 37" src="https://user-images.githubusercontent.com/106953442/179059971-e60516ce-fe95-433a-a4e0-37b630f41915.png">

**Comment by axelkirken** [comment]
Problemet löst och pushat till main

**Comment by tgadler** [comment]
Fantastiskt! Trodde det skulle bli en ordentlig huvudvärk. 👏

**Comment by axelkirken** [comment]
flexbox löser allt
