### ISSUE TITLE
VIll vi ha animationen i 58205ba65051e150742ce9031d8acea034a28e4a?

### ISSUE THREAD

**Issue by tgadler** [axelkirken/eminenthemsida#9]
Kanske? Kanske inte? Är kluven men den är lätt att ta bort. @axelkirken

**Comment by axelkirken** [comment]
Du menar att den glider ner? Tycker det är rätt snyggt. Däremot går det lite långsamt för texten att bli mörk när man hovrar över den, känns laggigt.

**Comment by tgadler** [comment]
Juste. Satte den svinhöt i felsökningssyfte... Fixar!
